services:
  postgres:
    image: postgres:14
    container_name: practice_postgres
    environment:
      POSTGRES_DB: competency_analysis
      POSTGRES_USER: practice_user
      POSTGRES_PASSWORD: practice_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: practice_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@practice.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: practice_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:

name: competency-practice